version: '*'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: application.py
    env_file:
      - .env
    volumes:
      - ./backend:/app  
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app 
      - /app/node_modules  
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  tensorflow:
    image: tensorflow/serving:latest
    ports:
      - "8501:8501"
    volumes:
      - ./tensorflow_models:/models
    environment:
      - MODEL_NAME=mnist_model
    command: >
      --port=8501 --rest_api_port=8501 --model_name=${MODEL_NAME}
      --model_base_path=/models/${MODEL_NAME}

volumes:
  db_data:
